base:
  api:
    url: http://22.22.22.22
    credential:
      username: foo
      password: bar
  # relative to current dir
  # set to null to disable sandbox
  sandbox: ../windows-container/winc.exe
  # relative to current dir
  runtimeDirectory: ../runtime
  compile:
    # WARN: config will be MERGED so that this section is tricky in `config.xxx.yaml`
    _base:
      timeout: 20000
      source: foo.c
      target: foo.exe
      sandboxArgs: --use-logon
    _vcenv:
      env:
        INCLUDE: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt
        LIB: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\lib\x86;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\um\x86
        PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\Hostx86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE;C:\Windows\system32;C:\Windows
    _gcc11:
      command: gcc
      args: -O2 -s -Wall -o foo.exe foo.c -lm -Wl,--stack=134217728 -std=c11 -m32
    _clang11:
      command: clang
      args: -O2 -Wall -o foo.exe foo.c -std=c11 -target i386-pc-win32 -fno-ms-compatibility
    _vc:
      command: cl
      args: /utf-8 /GS /GL /analyze- /W3 /Gy /Zc:wchar_t /Gm- /O2 /Zc:inline /fp:precise /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /WX- /Zc:forScope /Gd /Oy- /Oi /MD /EHsc /nologo foo.c
    gcc51c11:
      extend: [_base, _gcc11]
      env:
        PATH: C:\TDM-GCC-5.1\bin;C:\Windows\system32;C:\Windows
    gcc49c11:
      extend: [_base, _gcc11]
      env:
        PATH: C:\TDM-GCC-4.9\bin;C:\Windows\system32;C:\Windows
    msvc2017:
      extend: [_base, _vcenv, _vc]
    llvm40:
      extend: [_base, _vcenv, _clang11]
      env:
        PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\Hostx86\x86;C:\Program Files\LLVM4.0\bin;C:\Windows\system32;C:\Windows
  match:
    s1bin: ./challenger.exe
    s2bin: ./opponent.exe
    config: config.json
    summary: summary.json
    command: node
    # relative to the working directory
    args: ../../../reversi-judge/.dist/bootstrap.js --config config.json
  mq:
    connection:
      hostname: 22.22.22.22
      username: guest
      password: guest
      heartbeat: 30
