logger:
  path: logger

eventBus:
  path: eventBus

mq:
  path: mq
  inject:
    - logger

gmkcompile:
  path: gmkcompile
  inject:
    - mq
    - logger

gmkmatch:
  path: gmkmatch
  inject:
    - mq
    - logger

compileTest:
  path: compileTest
  inject:
    - logger
